server:
  port: 44000
  address: 0.0.0.0
spring:
  application:
    name: sleuthissue
  data:
    mongodb:
      uri: mongodb://sleuth:password@localhost:27017/SLEUTHISSUE
      database: SLEUTHISSUE
  sleuth:
    sampler:
      percentage: 0